---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="2.7.23"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.7.3"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="4.2.0"
  allow_failures:
  - env: PUPPET_GEM_VERSION="4.2.0"
notifications:
  email: false
